import type { Metadata } from "next"
import { Kadwa } from "next/font/google"
import "./globals.css"

const kadwa = Kadwa({
  weight: "400",
  variable: "--font-kadwa",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={`${kadwa.variable} `}>
      <body>{children}</body>
    </html>
  )
}
